apertureless/vue-chartjs

README.md, src/BaseCharts/Bar.js, src/BaseCharts/Doughnut.js, src/BaseCharts/Line.js, src/BaseCharts/Pie.js, src/BaseCharts/PolarArea.js, src/BaseCharts/Radar.js
Currently, the chartjs object is not properly destroyed (cleaning up event listeners etc) when the component is destroyed.
This pull request saves the chart instance on the component and adds a `destroy()` hook to the component that calls the chart instance's `.destroy()` method to ensure proper cleanup.
```js
methods: {
render (data, options = this.options) {
this._chart = new Chart( // save instance on a property of the vm
this.$els.canvas.getContext('2d'), {
type: 'bar',
data: data,
options: options
}
)
this._chart.generateLegend()
}
},
beforeDestroy () {
this._chart.destroy() //destroy chart when component is destroyed
}
```
=> Properly destroy chartjs objects

build/webpack.base.conf.js, package.json, src/BaseCharts/Bar.js, src/BaseCharts/Bubble.js, src/BaseCharts/Doughnut.js, src/BaseCharts/Line.js, src/BaseCharts/Pie.js, src/BaseCharts/PolarArea.js, src/BaseCharts/Radar.js, test/unit/specs/Bar.spec.js, test/unit/specs/Bubble.spec.js, test/unit/specs/Doughnut.spec.js, test/unit/specs/Line.spec.js, test/unit/specs/Pie.spec.js, test/unit/specs/PolarArea.spec.js, test/unit/specs/Radar.spec.js, yarn.lock
Based on #22 the template options got rewritten to pure render functions.
=> Feature/runtimebuild #22

test/unit/specs/Bar.spec.js, test/unit/specs/Bubble.spec.js, test/unit/specs/Doughnut.spec.js, test/unit/specs/Line.spec.js, test/unit/specs/Pie.spec.js, test/unit/specs/PolarArea.spec.js, test/unit/specs/Radar.spec.js
Add more test coverage for `beforeDestroy()` hooks to see if `chart.js` instance get destroyed.
=> ✅ Add tests for chart instance destroying

build/webpack.release.js, package.json
Add new webpack config for release build.
As most people using vue-chartjs in a pipeline with webpack or gulp the new release is not minified and the production env is not set.
This should fix #19 and #26
=> ✨ Add minimal release webpack config

package.json, yarn.lock
Update vue.js dependency to prevent errors that can occur because of [vue 2.1.7](https://github.com/vuejs/vue/releases/tag/v2.1.7)
=> 🐛 Fix #30 type error

src/mixins/reactiveData.js, src/mixins/reactiveProp.js
- Destroy chart instance on render()
- Add additional check for dataset length if dataset labels and datasets length missmatch
- Add comments
- Refactor reactiveData to match reactiveProp style
=> 🔨 Change reactiveMixins to fix #35

package.json
Added the `babilify` transform for `browserify` in `packge.json` so the `src` files can be transpiled in browserify projects.
Browserify applies transforms on a per-module basis and doesn't appear to allow global transforms, meaning that `babelify` needs to be declared in the modules `package.json` in order to transpile the `ES2015` code in `src`.
In order for a browserify user to transpile the code, they would need to install [babelify](https://www.npmjs.com/package/babelify) and [babel-preset-es2015](https://www.npmjs.com/package/babel-preset-es2015) and add a `.babelrc` file in the root of their project with the following code:
```
{ 
"presets": ["es2015"]
}
```
I think you could get away with explaining that rather than creating a dependency for `babelify` and `babel-preset-es2015` …
=> Added browserify support

dist/vue-chartjs.js, src/BaseCharts/HorizontalBar.js, src/examples/HorizontalBarExample.js, src/index.js, test/unit/specs/HorizontalBar.spec.js
To remove optional 'type' parameter at Bar component, which was ignored inside reactive mixins.
It was resulting in horizontal bars becoming vertical after dataset reactive change
Fix
- [* ] All tests passed
- OS: Windows 10 x64
- NPM Version: 3.10.10
=> separate HorizontalBar component added

build/webpack.release.js, package.json
This PR is an enhancement proposal focusing on the removal of all external deps (vue, graph.js, ...) from the final build and will also reduce minified build size from 500 kB to 59.1 kB.
=> Update release build to not include externals.

docs/ja/README.md
change only a document for #64
Link to vue.js guide in Limitation change to japanese guide https://jp.vuejs.org/
I guess no need test
- OS: Windows10 Creators Update 1703
- NPM Version:  3.10.8
=> translated README.md into Japanese

docs/pt-br/README.md
Enhancement
- [ X] All tests passed
- OS: MacOS Sierra v10.12.4
- NPM Version: 4.0.5
=> :memo: Add pt-br readme support

docs/README.md, docs/pt-br/README.md
Fix typo doc  in english and portuguese
- OS:  Windows10 Pro Creators Update 1703
- NPM Version: 3.10.8
=> Fix typo in docs

src/mixins/reactiveData.js, src/mixins/reactiveProp.js
A small consequence of replacing the entire dataset in the [reactive mixins files](https://github.com/apertureless/vue-chartjs/blob/develop/src/mixins/reactiveProp.js) is that it causes charts to completely re-render even if only the 'data' attribute of a dataset is changing. In my case, I set up a reactive doughnut chart with two data points but whenever the data values change, instead of shifting the fill coloring, it completely re-renders the entire chart.
You can see the issue in this fiddle (the problem remains even when changing chart type):
https://jsfiddle.net/sg0c82ev/11/
To solve the issue, I instead run a diff between the new and old dataset keys, remove keys that aren't present in the new data,  and update the rest of the attributes individually. After making these changes my …
=> Fix reactive mixins animation re-rendering issue.

src/mixins/reactiveData.js, src/mixins/reactiveProp.js
Reactive mixin broke if the initial data was set to null.
=> 🐛 Fix #122 reactive mixin

src/BaseCharts/Bar.js, src/BaseCharts/Bubble.js, src/BaseCharts/Doughnut.js, src/BaseCharts/HorizontalBar.js, src/BaseCharts/Line.js, src/BaseCharts/Pie.js, src/BaseCharts/PolarArea.js, src/BaseCharts/Radar.js
Implementation for feature #130
Possibility to add inline plugins to individual charts.
A plugin can be added in the class which extends any of the charts before rendering,
```
this.addPlugin({
id: 'kwhWeek',
beforeDraw(chart) {
const width = chart.chart.width;
const height = chart.chart.height;
const ctx = chart.chart.ctx;
ctx.restore();
const fontSize = (height / 114).toFixed(2);
ctx.font = `${fontSize}em sans-serif`;
ctx.textBaseline = 'middle';
const text = '4511kWh';
const textX = Math.round((width - ctx.measureText(text).width) / 2);
const textY = height / 2;
ctx.fillText(text, textX, textY);
ctx.save();
},
});
```
It supports all methods available in the docs http://www.chartjs.org/docs/latest/developers/plugins.html
=> Add support for inline plugins

src/BaseCharts/Bar.js, src/BaseCharts/Bubble.js, src/BaseCharts/Doughnut.js, src/BaseCharts/HorizontalBar.js, src/BaseCharts/Line.js, src/BaseCharts/Pie.js, src/BaseCharts/PolarArea.js, src/BaseCharts/Radar.js, src/BaseCharts/Scatter.js
If `renderChart()` was somehow not called before the component was destroyed, the component will raise an exception because `this._chart` is undefined. This patch ensures that `this._chart.destroy()` will only be called if `this._chart` has actually been initialized.
=> Fix beforeDestory when renderChart was not called

src/BaseCharts/Bar.js, src/BaseCharts/Bubble.js, src/BaseCharts/Doughnut.js, src/BaseCharts/HorizontalBar.js, src/BaseCharts/Line.js, src/BaseCharts/Pie.js, src/BaseCharts/PolarArea.js, src/BaseCharts/Radar.js, src/BaseCharts/Scatter.js
Fix
Remove nonsense code
https://github.com/chartjs/Chart.js/issues/2177
- OS: Ubuntu 16.04LTS
- NPM Version: 5.0.4
=> :pencil2: Remove generateLegend()  from initialization codes

docs/config.js, docs/zh-cn/README.md
=> Add Chinese simplified docs support.

.babelrc, package.json, src/helpers/options.js, yarn.lock
Fix for #190 
Replaced Object.assign with deepmerge to properly merge nested objects.
=> Replace Object.assign with deepmerge

docs/config.js, docs/fr-fr/README.md
Added French translation for README.md, as requested per #64.
Didn't run the tests.
- OS: Fedora 26
- NPM Version: 3.10.10
=> French translation for README.md

docs/config.js, docs/id/README.md
Enhancement
not running test
- OS: Win10
- NPM Version: 3.10.10
=> Add id docs readme support

package.json, yarn.lock
The diff is pretty self-explanatory. 'NODE_ENV=production' gets interpreted as a command on Windows. Updates cross-env as well, because why not.
- OS: Windows 10
- NPM Version: 5.0.3 / Yarn version 1.1.0
=> fix NODE_ENV=... on windows

README.md
`three shaking` > `tree shaking` on README :D
=> Fix typo on readme.md (Three shaking)

src/BaseCharts/Bar.js, src/BaseCharts/Bubble.js, src/BaseCharts/Doughnut.js, src/BaseCharts/HorizontalBar.js, src/BaseCharts/Line.js, src/BaseCharts/Pie.js, src/BaseCharts/PolarArea.js, src/BaseCharts/Radar.js, src/BaseCharts/Scatter.js, test/unit/specs/Bar.spec.js, test/unit/specs/Bubble.spec.js, test/unit/specs/Doughnut.spec.js, test/unit/specs/HorizontalBar.spec.js, test/unit/specs/Line.spec.js, test/unit/specs/Pie.spec.js, test/unit/specs/PolarArea.spec.js, test/unit/specs/Radar.spec.js, test/unit/specs/Scatter.spec.js
Implementation for feature-request #274.
Inline plugins can now be added using the `plugins` prop:
```javascript
// MonthlyIncome.vue
import { Line } from 'vue-chartjs'
export default {
mixins: Line,
props: ['data', 'options'],
mounted () {
this.renderChart(this.data, this.options)
}
}
```
```vue
<template>
<monthly-income :data={....}  :plugins="[chartJSPlugin]"/>
</template>
<script>
import MonthlyIncome from 'path/to/component/MonthlyIncome'
export default {
components: { MonthlyIncome },
....
}
</script>
```
I've also updated the existing test cases (to reflect the change from `plugins` to `_plugins`) and added new test cases to test this feature.
I would've also helped update the docs, but unfortunately I only know 3 of the 8 languages.
=> Add prop for inline plugins

src/mixins/reactiveData.js, src/mixins/reactiveProp.js, yarn.lock
=> fix(mixins): Check for chartjs instance before rendering chart

README.md
Either this is a typo or another type of error, the package doesn't work with "chartjs" dependency, it needs "chart.js".
=> Missing dot in NPM dependencies in README

docs/ja/README.md
The Japanese document that was delayed in maintenance was adapted to the latest English document.
The following content has been updated.
- add properties css-classes, styles in section of property
- add section of inline plugin
- add scatter example
- add section of Resources
- and refine tlanslation
Sorry, don't execute test. because modified only document.
=> update japanese docs

.babelrc
fix need {"decoratorsLegacy":true} in "@babel/stage-2" when we have a newest version of babel
- [ x] All tests passed
=> fix(babel): fix decorator error in new version of babel

src/BaseCharts.js
Before creating new instance we need to run destroy() on old instance if it is exists to avoid **Hovering over line chart shows old chart data** bug problem, which is described here:
https://github.com/chartjs/Chart.js/issues/920
https://github.com/jtblin/angular-chart.js/issues/187
Fix
- OS: Windows 7
- NPM Version: 6.1.0
=> Delete old chart.js instance first

docs/README.md, src/mixins/index.js
This will resolve #382
---
Added some vue events to the mixins based on different actions.
- `chart:render` - if the mixin performs a complete rerender
- `chart:destroy` - if the mixin deletes the chart object instance
- `chart:update` - if the mixin performs an update instead of a re-render
- `labels:update` - if new labels were set
- `xlabels:update` if new xLabels were set
- `ylabels:update` - if new yLabels were set
---
=> feat(events): Add events to reactiveMixins

docs/index.html
Hi! The documentation is not working, because **docute** version changed and now the module is exported as "Docute" and not "docute" (docute last version is 4 and the documentation is requesting the latest version of docute, but the documentation works with docute 3)
So I added the specific version of docute to render the documentation.
Hope it helps you!
```
Its a FIX!
- [ Ok ] All tests passed
- OS: Ubuntu 16.0.4
- NPM Version: 6.1.0
```
=> Fixed docute version requested from unpkg (Last compatible v3.4.12)

docs/.vuepress/config.js
This PR enable the vuepress recommended search DocSearch on your website such as https://cli.vuejs.org/
[![Demo](https://cl.ly/c31ef642545a/download/Screen%20Recording%202019-05-29%20at%2009.31%20AM.gif)](https://vue-chartjs-docsearch.surge.sh/) 
You can [try it live here](https://vue-chartjs-docsearch.surge.sh/)
=> docs: enhance search on the documentation

README.md
Under the Reactive data section in the readme, the _More info here_ link only takes the reader to the main vue-chartjs homepage.
I'm proposing that since this section is talking about updating data, we can direct users to the Updating charts section of the docs, since it's still within the same realm and will provide meaningful context for developers who are looking for this info.
(not needed since it's just documentation)
- OS: Mac OS mojave
- NPM Version: 6.11.3
:pray:
=> docs: Update 'More info here' link in readme doc

docs/ja/guide/README.md
It can be same as **Chart with props** code.
=> Comma is missing only in japanese docs.

docs/guide/README.md
Noticed quite a few grammatical issues in the guide, went ahead and fixed them. Some formatting with code blocks was changed as well.
Fix
- OS: not applicable
- NPM Version: not applicable
=> docs: Fix grammatical issues in the guide

docs/ja/guide/README.md
I also fixed a typo (`独自のの` -> `独自の`).
=> docs: Remove redundant English from Japanese document

package.json, types/components.d.ts, types/mixins.d.ts
- OS: OSX
- NPM Version: 13.3.0
feel free to just close this PR and copy the code to your repo if you have issues with it
#614
=> fix: Fix typescript issue #614

README.md
Resolves #638
The problem was that the example was causing typescript error as described in
https://github.com/apertureless/vue-chartjs/issues/638
The solution is updating the docs as propsed in https://github.com/apertureless/vue-chartjs/issues/638#issuecomment-704894493
Fix
- OS: Any
- NPM Version: Any
=> chore(docs): Fix readme typescript example type error

docs/guide/README.md
Documentation update.
Charts don't show if the package is installed like this:
`npm install vue-chartjs chart.js --save
`
Instead we need to install with the lowe version of chart.js.
`npm install vue-chartjs chart.js@2.9.4
`
=> docs: Update npm and yarn installation command to 'chart.js@2.9.4'.

legacy/src/Charts.js, legacy/src/index.js
fix #783
fix https://github.com/apertureless/vue-chartjs/issues/783#issue-1183457021
=> add missed export for legacy charts generateChart func

legacy/src/Charts.js
fix the error, when multiple charts can't render on one page
from issues #800 #801
=> fix(legacy-charts): fix render multiple charts at one page

legacy/src/Charts.js, website/src/guide/index.md
Fix [bug](#801) updating multiple reactive charts on one page, except when using the chartjs-plugin-annotation and Vue 2 simultaneously.
=> Fix reactive charts update

legacy/src/Charts.js
tune legacy charts options type check
=> fix(legacy-charts): tune chartoptions type check

README.md, legacy/src/Charts.js, src/BaseCharts.ts, src/utils.ts, website/src/guide/index.md
Add reactivity to options.  expose chart and updateChart function
#805
=> Add reactivity to options

.eslintignore, .gitignore, legacy/package.json, package.json
add typescript definitions for legacy charts
#825
=> feat(legacy-charts): add typescript definitions for legacy charts

legacy/src/Charts.js
Fixed https://github.com/apertureless/vue-chartjs/issues/825
Add type comment on Chart Objects.
Emitted definitions are typed, by regarding Chart Objects (e.g. Bar, Bubble) as a `Object` 
- OS: macOS 12.0.1
- NPM Version: 8.5.5
=> fix: add type comment on Chart Objects (#825)

website/src/guide/index.md
Replace "asyncronous" with the correct spelling "asynchronous"
- OS: n/a
- NPM Version: n/a
=> docs: fix typo in guide

README.md, website/src/guide/index.md
Update `PluginOptionsByType` in doc examples to `Plugin`
Missed spots from https://github.com/apertureless/vue-chartjs/commit/65762c893175b1d24245020e2ff74d3ba633a6fa
- OS: n/a
- NPM Version: n/a
=> docs: fix Plugin type import

.size-limit.json, src/typedCharts.ts, src/utils.ts, website/src/migration-guides/index.md
=> fix: fix compatability with Vue >=2.7

README.md
**Install** & **How To Use** links were not working because the headings were not present. So I have replaced both of them with a **QuickStart** link whose corresponding heading is present :)
=> [Docs]: Add QuickStart Navigation link replacing "Install" & "How to Use" links

README.md, src/chart.ts, src/props.ts, website/src/api/index.md, website/src/guide/index.md
=> feat(a11y): support ARIA attributes, role and fallback content for canvas

website/src/kr/api/index.md, website/src/kr/guide/index.md, website/src/kr/index.md
As a Korean, I thought it would be nice to have a Korean version of the docs document, so I translated the document.
(issue #400)
- OS: Ubuntu Linux 20.04
- NPM Version: n/a
=> docs: Translate to korean

website/src/guide/index.md, website/src/kr/guide/index.md
I wanted to update the `Updating Charts` section as some (including myself) faced an issue where Vue logs warnings regarding the updated chartData as `read-only`.
Discussion: https://github.com/apertureless/vue-chartjs/issues/1039
=> Updates to `Updating Charts` documentation

src/typedCharts.ts
https://github.com/apertureless/vue-chartjs/issues/1058
As you can see in the original issue, there is a problem with Bar chart typing (other charts maybe also have it). The **Data** type is not fully correct since `Bar` chart can accept other data types apart from the described ones in the `typedCharts.d.ts`.
There's a new type named `ExtendedDataPoint` which represents objects like `{ x: 1, y: 2 }`, `{ id: 'Sales', nested: {value: 1500}` and so on. Based on https://www.chartjs.org/docs/latest/general/data-structures.html
=> fix(types): bar chart data

src/chart.ts, src/props.ts
Fixes https://github.com/apertureless/vue-chartjs/issues/579
The original issue was marked as completed, but it was not fixed. To address this issue, I've added a new prop that delays calling `destroy` on unMount. No matter how long your transition is, you can adjust the charts as a result
https://github.com/apertureless/vue-chartjs/assets/4270980/e79527aa-9b3f-44a0-9e09-44bff5411a9d 
https://github.com/apertureless/vue-chartjs/assets/4270980/c469443e-b656-46e3-89c3-17e151dcb85e
=> Add destroyDelay prop
