apertureless/vue-chartjs

src/BaseCharts/Bubble.js
src/index.js

Enhancement: Added Bubble chart

Added bubble chart type

---

src/BaseCharts/Bar.js

- OS: Mac OS
- NPM Version: 3.10.3

add horizontal bar parameter

---

src/mixins/reactiveData.js
src/mixins/reactiveProp.js

- Replaced complete dataset object instead only the data inside.

🐛 Fix reactiveMixins issue #42

---

.github/ISSUE_TEMPLATE.md

📝 Update github issue template

---

docs/README.md

Fix typo for legacy tag

---

docs/README.md

There is no -s flag (https://github.com/yarnpkg/yarn/issues/2532)

Removed -s flag from yarn command in docs

---

docs/README.md

fix a typo in an example

---

docs/README.md

Add a list of tutorials to docs page

📝 Add resources & tutorials to docs

---

docs/de/README.md
docs/ja/README.md
docs/pt-br/README.md

Fix
- OS: Ubuntu 16.04LTS
- NPM Version: 5.0.4

Fix links to images in translated documents

---

src/examples/ScatterExample.js

- OS: MacOS
- NPM Version: 5.3.0

Remove useless labels

---

package.json
yarn.lock

Update peerDependency Vue to 2.4.2

⬆️ Update dependency vue to 2.4.2

---

package.json
src/helpers/options.js
test/unit/specs/helpers/options.spec.js
yarn.lock

Remove lodash merge as a dependency and replace with `Object.assign()`

remvove lodash merge

---

src/BaseCharts/Bar.js
src/BaseCharts/Bubble.js
src/BaseCharts/Doughnut.js
src/BaseCharts/HorizontalBar.js
src/BaseCharts/Line.js
src/BaseCharts/Pie.js
src/BaseCharts/PolarArea.js
src/BaseCharts/Radar.js
src/BaseCharts/Scatter.js

This will fix #176
Signed-off-by: Jakub Juszczak <netghost03@gmail.com>

🔥 Remove default styles object as it causes problems

---

docs/ru/README.md

Some fixes inaccuracies in Russian translation for #64 

Fix inaccuracies in Russian translation

---

docs/README.md

- Fix some spelling mistakes
- Apply consistent naming for Vue and Chart.js
- Minor text changes

✏️ Spelling in docs

---

docs/fr-fr/README.md

Made some small edits to French README.MD

---

docs/README.md

Sorry, it was very annoying to me.
Enhancement
Github web edit

Typo fix in EN docs

---

README.md
docs/README.md
src/BaseCharts.js
src/examples/App.vue
src/examples/CustomExample.js

With this PR the `generateChart()` function will be exported. And can be used to create custom charts like mentioned in #326
---

Custom Charts

---

docs/id/README.md

Updating the Indonesian document.
The updated content:
- Refine translation to more formal terms in Indonesian language.
- Fix few typhos
- Introduction part: replace second paragraph according to the newer version of English document
- Add Custom/New Charts translation
- Remove Browser, Browserify, Webpack translation
- OS: Linux, Debian Jessie
- NPM Version: 5.6.0

Update and refine Indonesian translation

---

docs/ja/README.md

The Japanese document that was delayed in maintenance was adapted to the latest English document.
The following content has been updated.
add section custom chart example
delete section Explanation of Different Builds
and refine tlanslation
Sorry, don't execute test. because modified only document.

Update japanese docs with custom chart example.

---

types/index.d.ts

Added types for mixins (#378).
- Fix
- OS: Ubuntu 18.04
- NPM Version: 5.6.0

fix: typescript types for mixins (#378)

---

docs/README.md
src/BaseCharts.js

As this is used quite often this wrapper function will improve the UX of generating a legend

feat(ux): Add a wrapper around generateLegend

---

docs/README.md

fixed code example in the docs

---

README.md

Remove an unnecessary backquote.
Please accept.

Fix typo of Readme

---

docs/README.md

Added missing commas in example snippet

---

docs/config.js

- reordered languages alphabetically by language code
- removed `de` language

Updated languages dropdown and fixed Indonesian url

---

docs/guide/README.md

+ Typo Fix

---

README.md

Fix
- OS: MacOS
- NPM Version: 6.4.1

Fix spelling error in README.md code examples

---

README.md

Docs: add typescript usage

---

docs/ja/README.md
docs/ja/api/README.md
docs/ja/guide/README.md

Modified Japanese new document. issue #400 

Tlanslate docs to japanese #400

---

docs/ja/README.md

Corrected the link to the guide page to the Japanese page.

fix #492 link to Japanese guide page

---

types/index.d.ts
types/mixins.d.ts

feat(typescript): Improve mixins type definitions

---

docs/README.md
docs/fr-fr/README.md
docs/id/README.md
docs/pt-br/README.md
docs/ru/README.md
docs/zh-cn/README.md

Documentation fix ("powerfull" => "powerful")
N/A
- OS: N/A
- NPM Version: N/A

docs: Update README.md

---

docs/guide/README.md

docs: fix indentations and `chartdata` data property

---

docs/.vuepress/config.js
docs/zh-cn/README.md
docs/zh-cn/api/README.md
docs/zh-cn/guide/README.md

- OS:  Windows 10
- NPM Version: v6.4.1

docs: Chinese docs #400

---

types/components.d.ts

I cant run test because phantomJS problem, but I think this will not affect any code.
This commit fixed wrong type of `addPlugin`.
- OS: OSX 10.14.6
- NPM Version: 6.10.2

fix: fix add plugin type

---

docs/guide/README.md

docs: Update.README.md

---

README.md

Took me a while to find the correct way to do it, so it probably won't hurt to document it.

docs: Added a mixin to TS example

---

docs/.vuepress/config.js
docs/guide/README.md
docs/pt-br/README.md
docs/pt-br/api/README.md
docs/pt-br/guide/README.md

- OS: Linux Mint 19.3 Tricia
- YARN Version: 1.22.4

docs: Translate pt-br

---

docs/guide/README.md

docs: Set global defaults

---

.github/workflows/ci.yml
README.md
package.json

add github actions for ci
- OS: macOs BigSur
- NPM Version: 7.21.1

refactor: add github actions for ci

---

.storybook/.babelrc
.storybook/main.js
.storybook/manager.js
.storybook/preview.js
.storybook/theme.js
package.json
stories/bar.stories.js
stories/bubble.stories.js
stories/custom.stories.js
stories/doughnut.stories.js
stories/horizontalBar.stories.js
stories/line.stories.js
stories/pie.stories.js
stories/polarArea.stories.js
stories/radar.stories.js
stories/reactive.stories.js
stories/reactiveProp.stories.js
stories/scatter.stories.js
yarn.lock

Add storybook and stories for sandbox components
- NPM Version: 6.14.15

Add storybook

---

docs/ja/guide/README.md

The latest version of chart.js is not compatible to the vue-chart.js.
Fix

docs: Change install command for Japanese doc

---

.clean-publish
.gitignore
package.json
pnpm-lock.yaml
rollup.config.js

Add clean-publish and create publishConfig
- NPM Version: 6.14.15

refactor: add publishCongif and clean-publish package

---

.github/renovate.json

feat: add renovate bot

---

.github/workflows/release.yml
package.json
pnpm-lock.yaml

Add script for release package and publish action for Github.

Add release script

---

README.md

add cube branding and change readme header style

Add cube branding

---

README.md

docs(readme): change images source

---

legacy/sandboxes/bar/package.json
legacy/sandboxes/bubble/package.json
legacy/sandboxes/doughnut/package.json
legacy/sandboxes/line/package.json
legacy/sandboxes/pie/package.json
legacy/sandboxes/polar-area/package.json
legacy/sandboxes/radar/package.json
legacy/sandboxes/scatter/package.json
sandboxes/bar/package.json
sandboxes/bubble/package.json
sandboxes/custom/package.json
sandboxes/doughnut/package.json
sandboxes/line/package.json
sandboxes/pie/package.json
sandboxes/polar-area/package.json
sandboxes/radar/package.json
sandboxes/reactive-prop/package.json
sandboxes/reactive/package.json
sandboxes/scatter/package.json
website/src/index.md
website/src/ja/index.md
website/src/pt-br/index.md
website/src/ru/index.md
website/src/zh-cn/index.md

fix website main image path and update package version at sandboxes

docs: fix main image path and update package version at sandboxes

---

legacy/src/Charts.js

fix: Fix typo in chartDestroy

---

pnpm-lock.yaml

chore: fix lockfile conflicts

---

README.md
website/src/.vitepress/config.ts
website/src/guide/index.md
website/src/migration-guides/index.md

add guide for migration from vue-chart-3

docs: add guide for migration from vue-chart-3

---

.github/workflows/checks.yml
.github/workflows/ci.yml
.github/workflows/release.yml
.npmrc

up pnpm version at github actions and add npmrc file

chore: up pnpm version at github actions and add npmrc file

---

.github/renovate.json
legacy/sandboxes/bar/package.json
legacy/sandboxes/bubble/package.json
legacy/sandboxes/doughnut/package.json
legacy/sandboxes/line/package.json
legacy/sandboxes/pie/package.json
legacy/sandboxes/polar-area/package.json
legacy/sandboxes/radar/package.json
legacy/sandboxes/scatter/package.json
sandboxes/bar/package.json
sandboxes/bubble/package.json
sandboxes/custom/package.json
sandboxes/doughnut/package.json
sandboxes/line/package.json
sandboxes/pie/package.json
sandboxes/polar-area/package.json
sandboxes/radar/package.json
sandboxes/reactive-prop/package.json
sandboxes/reactive/package.json
sandboxes/scatter/package.json

update chart.js version at sandboxes package.json

docs: update chart.js version at sandboxes package.json

---

.github/workflows/checks.yml
.github/workflows/ci.yml
.github/workflows/release.yml
pnpm-lock.yaml

ci: update pnpm

---

website/src/.vitepress/config.ts

docs: fix algolia apiKey and appId based on new migration

---

website/src/guide/index.md

docs: remove unsupported peer dependency chart.js v2

---

website/src/.vitepress/config.ts

docs: fix edit on GitHub link

---

website/src/migration-guides/index.md

Docs update
- OS: Ubuntu 20.04
- NPM Version: 8.1.2
-------------
We had some performance issues in our Vue 2.7 project when using `legacy` variant. After changing `import` to use normal, non-legacy version, everything seems to work fine and the performance issue also got solved.

docs: update Vue version info in migration guide

---

src/index.ts

default export was removed
BREAKING CHANGE: default export was removed

refactor: remove default export

---

.size-limit.json
sandboxes/events/index.html
sandboxes/events/index.ts
sandboxes/events/package.json
sandboxes/events/src/App.vue
sandboxes/events/src/chartConfig.ts
sandboxes/events/vite.config.js
src/index.ts
src/utils.ts
stories/chart.stories.ts

utils to handle chart clicks were added

feat: events utils

---

website/src/migration-guides/index.md

Mistyping corrected

---

src/chart.ts

https://github.com/apertureless/vue-chartjs/issues/1043

Use nextTick to apply chart props change
